version: "3.8"
services:
  book_catalog:
    build: ./book_catalog
    environment:
      DATABASE_URL: "postgresql://assessment_part_2_user:QJVGtCXlv9JULkLi34Ou7MCc4b9vcGvl@dpg-cripj5jv2p9s738mbqvg-a.singapore-postgres.render.com/assessment_part_2"
    ports:
      - "8001:8000"
    depends_on:
      - db

  inventory_management:
    build: ./inventory_management
    environment:
      DATABASE_URL: "postgresql://assessment_part_2_user:QJVGtCXlv9JULkLi34Ou7MCc4b9vcGvl@dpg-cripj5jv2p9s738mbqvg-a.singapore-postgres.render.com/assessment_part_2"
    ports:
      - "8002:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: assessment_part_2
      POSTGRES_USER: assessment_part_2_user
      POSTGRES_PASSWORD: QJVGtCXlv9JULkLi34Ou7MCc4b9vcGvl
    ports:
      - "5432:5432"