apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: assessment7acr.azurecr.io/book_catalog:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://assessment_part_2_user:QJVGtCXlv9JULkLi34Ou7MCc4b9vcGvl@dpg-cripj5jv2p9s738mbqvg-a.singapore-postgres.render.com/assessment_part_2"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: assessment7acr.azurecr.io/inventory_management:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://assessment_part_2_user:QJVGtCXlv9JULkLi34Ou7MCc4b9vcGvl@dpg-cripj5jv2p9s738mbqvg-a.singapore-postgres.render.com/assessment_part_2"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8000
  type: LoadBalancer